services:
  router:
    environment:
      APP_ENV: staging
      PG_SCHEMA: staging
      ROUTER_DB_MAX_CONNS: 4
      ROUTER_DB_MIN_CONNS: 1

  functions:
    environment:
      APP_ENV: staging
      PG_SCHEMA: staging
      FUNCTIONS_DB_MAX_CONNS: 3
      FUNCTIONS_DB_MIN_CONNS: 1

  ingestor:
    environment:
      APP_ENV: staging
      PG_SCHEMA: staging

  loader:
    environment:
      APP_ENV: staging
      PG_SCHEMA: staging

  powersync:
    environment:
      APP_ENV: staging
      PG_SCHEMA: staging
